/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClienteSchema extends BaseModel {
  static $columns = ['cidade', 'cpf', 'createdAt', 'email', 'estado', 'id', 'nome', 'numero', 'rua', 'senha', 'updatedAt'] as const
  $columns = ClienteSchema.$columns
  @column()
  declare cidade: string | null
  @column()
  declare cpf: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare estado: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string | null
  @column()
  declare numero: string | null
  @column()
  declare rua: string | null
  @column()
  declare senha: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContaCorrenteSchema extends BaseModel {
  static $columns = ['agencia', 'clienteId', 'createdAt', 'id', 'numeroConta', 'saldo', 'updatedAt'] as const
  $columns = ContaCorrenteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare clienteId: number
  @column()
  declare numeroConta: string
  @column()
  declare agencia: string
  @column()
  declare saldo: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MovimentacaoSchema extends BaseModel {
  static $columns = ['contaDestinoId', 'contaOrigemId', 'createdAt', 'descricao', 'id', 'tipo', 'updatedAt', 'valor'] as const
  $columns = MovimentacaoSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare contaOrigemId: number
  @column()
  declare contaDestinoId: number | null
  @column()
  declare tipo: 'deposito' | 'saque' | 'transferencia' | 'aplicacao' | 'resgate'
  @column()
  declare valor: number
  @column()
  declare descricao: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvestimentoSchema extends BaseModel {
  static $columns = ['clienteId', 'createdAt', 'dataAplicacao', 'dataResgate', 'id', 'tipo', 'valorInvestido', 'updatedAt'] as const
  $columns = InvestimentoSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare clienteId: number
  @column()
  declare tipo: 'poupanca' | 'titulos' | 'acoes'
  @column()
  declare valorInvestido: number
  @column.dateTime()
  declare dataAplicacao: DateTime
  @column.dateTime({ serializeAs: null })
  declare dataResgate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
